from typing import Protocol
from .responses import SecretData


class SecretClient(Protocol):
    def get_secret_by_key(self, secret_key: str) -> SecretData | None: ...

    def get_secret_by_id(self, secret_id: str) -> SecretData | None: ...

    def write_secret_id(self, value: str) -> SecretData: ...

    def write_secret_key(self, key: str, value: str) -> SecretData: ...
